version: "3.8"

services:
  postgres:
    image: postgres:${POSTGRES_VERSION:-15-alpine}
    container_name: pizzanat-postgres
    restart: always
    environment:
      POSTGRES_DB: pizzanat_db
      POSTGRES_USER: pizzanat_user
      POSTGRES_PASSWORD: ${DB_PASSWORD:-strong_password_change_me}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pizzanat_user -d pizzanat_db"]
      interval: ${HEALTH_CHECK_INTERVAL:-10s}
      timeout: ${HEALTH_CHECK_TIMEOUT:-5s}
      retries: ${HEALTH_CHECK_RETRIES:-5}
    networks:
      - pizzanat-network

  app:
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/pizzanat_db
      SPRING_DATASOURCE_USERNAME: pizzanat_user
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-strong_password_change_me}

volumes:
  postgres-data:

networks:
  pizzanat-network:
    name: pizzanat-network
