version: "3.8"

# Оптимизированная версия для Timeweb Clou
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.optimized
    container_name: pizzanat-app
    restart: unless-stopped

    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s

    environment:
      # Spring настройки
      SPRING_PROFILES_ACTIVE: prod
      SERVER_PORT: 8080

      # JVM оптимизация для Timeweb Cloud
      JAVA_OPTS: >-
        -XX:+UseContainerSupport
        -XX:MaxRAMPercentage=70.0
        -XX:+ExitOnOutOfMemoryError
        -XX:+UseG1GC
        -Djava.security.egd=file:/dev/./urandom
        -Dspring.jmx.enabled=false

      # База данных Timeweb
      #SPRING_DATASOURCE_URL: ${TIMEWEB_DB_URL:-jdbc:postgresql://45.95.235.22:5432/default_db}
      SPRING_DATASOURCE_URL: ${TIMEWEB_DB_URL:-jdbc:postgresql://45.10.41.59:5432/default_db}
      SPRING_DATASOURCE_USERNAME: ${TIMEWEB_DB_USER:-user}
      # SPRING_DATASOURCE_PASSWORD: ${TIMEWEB_DB_PASSWORD:-strong_password_change_me}
      SPRING_DATASOURCE_PASSWORD: ${TIMEWEB_DB_PASSWORD:-111111111!}

      # Пул соединений оптимизированный для облака
      SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: 8
      SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: 2
      SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: 30000
      SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT: 300000
      SPRING_DATASOURCE_HIKARI_MAX_LIFETIME: 1200000
      SPRING_DATASOURCE_HIKARI_LEAK_DETECTION_THRESHOLD: 60000

      # S3 Timeweb настройки
      TIMEWEB_S3_ACCESS_KEY: ${TIMEWEB_S3_ACCESS_KEY:-AJK63DSBOEBQD3IVTLOT}
      TIMEWEB_S3_SECRET_KEY: ${TIMEWEB_S3_SECRET_KEY:-eOkZ8nzUkylhcsgPRQVJdr8qmvblxvaq7zoEcNpk}
      TIMEWEB_S3_ENDPOINT: ${TIMEWEB_S3_ENDPOINT:-https://s3.twcstorage.ru}
      TIMEWEB_S3_BUCKET: ${TIMEWEB_S3_BUCKET:-f9c8e17a-pizzanat-products}
      TIMEWEB_S3_PUBLIC_URL: ${TIMEWEB_S3_PUBLIC_URL:-https://s3.twcstorage.ru/f9c8e17a-pizzanat-products}

      # Кэширование
      SPRING_CACHE_TYPE: simple

      # JWT настройки
      JWT_SECRET: ${JWT_SECRET:-"YTg1MmViNjM0MWY5MTk4NTk1OWM4YzhjZTRlMjIzMTZmNWI1ODk3YmY3YmI3NjhjNWFmYTU1NDYzY2E3OGVmMg=="}

      # Логирование оптимизированное для production
      LOGGING_LEVEL_ROOT: WARN
      LOGGING_LEVEL_COM_BAGANOV: INFO
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB: WARN
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: WARN
      LOGGING_PATTERN_CONSOLE: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

      # Actuator для мониторинга
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,info,metrics
      MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: never
      MANAGEMENT_ENDPOINT_HEALTH_ENABLED: true
      MANAGEMENT_SERVER_PORT: 8080

      # Spring Boot оптимизации
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_JPA_SHOW_SQL: false
      SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_BATCH_SIZE: 25
      SPRING_JPA_PROPERTIES_HIBERNATE_ORDER_INSERTS: true
      SPRING_JPA_PROPERTIES_HIBERNATE_ORDER_UPDATES: true
      SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_BATCH_VERSIONED_DATA: true

      # Telegram Gateway настройки
      TELEGRAM_GATEWAY_ENABLED: true
      TELEGRAM_GATEWAY_ACCESS_TOKEN: ${TELEGRAM_GATEWAY_ACCESS_TOKEN:-AAGCGwAAIlEzNcCeEbrV5r-w65s_0edegXThOhJ2nq-eBw}
      TELEGRAM_GATEWAY_MESSAGE_TTL: 300
      TELEGRAM_GATEWAY_CALLBACK_URL: ${TELEGRAM_GATEWAY_CALLBACK_URL:-https://debaganov-pizzanat-0177.twc1.net/api/v1/auth/telegram-gateway/callback}
      TELEGRAM_GATEWAY_TIMEOUT_SECONDS: 10
      TELEGRAM_GATEWAY_MAX_RETRY_ATTEMPTS: 3

      # Telegram Auth настройки
      TELEGRAM_AUTH_ENABLED: true
      TELEGRAM_AUTH_BOT_TOKEN: ${TELEGRAM_AUTH_BOT_TOKEN:-7819187384:AAGJNn0cwfJ7Nsv_N25h75eggEmqmD5WZG4}
      TELEGRAM_AUTH_BOT_USERNAME: ${TELEGRAM_AUTH_BOT_USERNAME:-PizzaNatBot}
      TELEGRAM_AUTH_WEBHOOK_URL: ${TELEGRAM_AUTH_WEBHOOK_URL:-https://debaganov-pizzanat-0177.twc1.net/api/v1/telegram/webhook}
      TELEGRAM_AUTH_WEBHOOK_ENABLED: true
      TELEGRAM_AUTH_TOKEN_TTL_MINUTES: 10
      TELEGRAM_AUTH_RATE_LIMIT_PER_HOUR: 5

      # SMS настройки
      # SMS_ENABLED: true
      # SMS_API_KEY: ${SMS_API_KEY:1234567890}
      # SMS_SENDER_ID: ${SMS_SENDER_ID:1234567890}
      # SMS_RATE_LIMIT_PER_HOUR: 5

      # Telegram Bot настройки (основные уведомления) - ОТКЛЮЧЕНЫ
      TELEGRAM_ENABLED: ${TELEGRAM_ENABLED:-true}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_AUTH_BOT_TOKEN:-7819187384:AAGJNn0cwfJ7Nsv_N25h75eggEmqmD5WZG4}
      TELEGRAM_API_URL: https://api.telegram.org/bot

      # Telegram Long Polling настройки (команды бота) - ОТКЛЮЧЕНЫ
      TELEGRAM_LONGPOLLING_ENABLED: ${TELEGRAM_LONGPOLLING_ENABLED:-false}
      TELEGRAM_BOT_ENABLED: ${TELEGRAM_BOT_ENABLED:-true}

      # Админский Telegram Bot настройки - ОТКЛЮЧЕН
      TELEGRAM_ADMIN_BOT_ENABLED: ${TELEGRAM_ADMIN_BOT_ENABLED:-true}
      TELEGRAM_ADMIN_BOT_TOKEN: ${TELEGRAM_ADMIN_BOT_TOKEN:-8052456616:AAEoAzBfr3jRpylDmxR-azNBSqimthPCHeg}
      TELEGRAM_ADMIN_BOT_USERNAME: ${TELEGRAM_ADMIN_BOT_USERNAME:-PizzaNatOrders_bot}
      TELEGRAM_ADMIN_BOT_MAX_RETRIES: 3
      TELEGRAM_ADMIN_BOT_TIMEOUT_SECONDS: 30

    ports:
      - "80:80"
      - "443:443"
    # ports:
    #   - "8080:8080"
