version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: pizzanat-postgres
    restart: always
    environment:
      POSTGRES_DB: pizzanat_db
      POSTGRES_USER: pizzanat_user
      POSTGRES_PASSWORD: ${DB_PASSWORD:-strong_password_change_me}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pizzanat_user -d pizzanat_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pizzanat-network

  redis:
    image: redis:7-alpine
    container_name: pizzanat-redis
    restart: always
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-strong_redis_password_change_me}
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pizzanat-network

  minio:
    image: "minio/minio:latest"
    container_name: pizzanat-minio
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - "MINIO_ROOT_USER=accesskey"
      - "MINIO_ROOT_PASSWORD=secretkey"
    volumes:
      - minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - pizzanat-network

  minio-init:
    image: minio/mc
    container_name: pizzanat-minio-init
    depends_on:
      minio:
        condition: service_healthy
    volumes:
      - ./src/main/resources/images:/images
      - ./init-scripts:/scripts
    entrypoint: >
      /bin/sh -c "
        chmod +x /scripts/minio-init.sh &&
        /scripts/minio-init.sh
      "
    environment:
      - MINIO_HOST=minio:9000
      - MINIO_ACCESS_KEY=accesskey
      - MINIO_SECRET_KEY=secretkey
      - BUCKET_NAME=pizzanat
    healthcheck:
      test: ["CMD", "curl", "-f", "http://minio:9000/minio/health/ready"]
      interval: 15s
      timeout: 13s
      retries: 5
    restart: on-failure
    networks:
      - pizzanat-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pizzanat-app
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/pizzanat_db
      SPRING_DATASOURCE_USERNAME: pizzanat_user
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-strong_password_change_me}
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_PASSWORD: ${REDIS_PASSWORD:-strong_redis_password_change_me}
      S3_ACCESS_KEY: accesskey
      S3_SECRET_KEY: secretkey
      S3_ENDPOINT: http://minio:9000
      S3_PUBLIC_URL: ${S3_PUBLIC_URL:-http://localhost/}
      S3_BUCKET: pizzanat
      JWT_SECRET: "YTg1MmViNjM0MWY5MTk4NTk1OWM4YzhjZTRlMjIzMTZmNWI1ODk3YmY3YmI3NjhjNWFmYTU1NDYzY2E3OGVmMg=="
      SPRING_MAIL_HOST: ${MAIL_HOST:-smtp.example.com}
      SPRING_MAIL_PORT: ${MAIL_PORT:-587}
      SPRING_MAIL_USERNAME: ${MAIL_USERNAME:-mail@example.com}
      SPRING_MAIL_PASSWORD: ${MAIL_PASSWORD:-mail_password}
      APP_NOTIFICATION_EMAIL_FROM: ${NOTIFICATION_EMAIL:-no-reply@pizzanat.com}
      APP_NOTIFICATION_EMAIL_ENABLED: ${NOTIFICATION_ENABLED:-false}
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8080"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - pizzanat-network

  # Опционально: добавление прокси-сервера nginx для SSL и балансировки
  nginx:
    image: nginx:alpine
    container_name: pizzanat-nginx
    restart: always
    depends_on:
      app:
        condition: service_started
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - pizzanat-network

networks:
  pizzanat-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
  minio-data:
