version: "3.8"

# Оптимизированная версия для Timeweb Cloud с переменными окружения
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.optimized
    container_name: pizzanat-app
    restart: unless-stopped

    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/health"]
      interval: ${HEALTH_CHECK_INTERVAL:-30s}
      timeout: ${HEALTH_CHECK_TIMEOUT:-10s}
      retries: ${HEALTH_CHECK_RETRIES:-3}
      start_period: ${HEALTH_CHECK_START_PERIOD:-90s}

    environment:
      # Spring настройки
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-prod}
      SERVER_PORT: ${SERVER_PORT:-8080}

      # JVM оптимизация для Timeweb Cloud
      JAVA_OPTS: >-
        -XX:+UseContainerSupport
        -XX:MaxRAMPercentage=${JVM_MAX_RAM_PERCENTAGE:-70.0}
        -XX:+ExitOnOutOfMemoryError
        -XX:+UseG1GC
        -Djava.security.egd=file:/dev/./urandom
        -Dspring.jmx.enabled=false
        -Duser.timezone=${JVM_TIMEZONE:-Europe/Moscow}

      # Временная зона для контейнера
      TZ: ${CONTAINER_TIMEZONE:-Europe/Moscow}

      # CORS настройки для поддержки фронтенда
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS:-https://pizzanat.ru,https://www.pizzanat.ru,https://api.pizzanat.ru,http://localhost:5173,http://localhost:3000,http://localhost:8080}
      CORS_ALLOWED_METHODS: ${CORS_ALLOWED_METHODS:-GET,POST,PUT,DELETE,OPTIONS,PATCH}
      CORS_ALLOWED_HEADERS: ${CORS_ALLOWED_HEADERS:-Authorization,Content-Type,X-Requested-With,Accept,Origin,X-Auth-Token,Cache-Control,X-Client-Type,X-Client-Version}
      CORS_EXPOSED_HEADERS: ${CORS_EXPOSED_HEADERS:-Authorization,Content-Type,X-Total-Count,X-Pagination-Page,X-Pagination-Size}
      CORS_ALLOW_CREDENTIALS: ${CORS_ALLOW_CREDENTIALS:-true}
      CORS_MAX_AGE: ${CORS_MAX_AGE:-3600}

      # База данных Timeweb (пароль остается как переменная окружения без значения по умолчанию)
      SPRING_DATASOURCE_URL: ${TIMEWEB_DB_URL:-jdbc:postgresql://45.10.41.59:5432/default_db}
      SPRING_DATASOURCE_USERNAME: ${TIMEWEB_DB_USER:-gen_user}
      SPRING_DATASOURCE_PASSWORD: ${TIMEWEB_DB_PASSWORD:-bv12345!}

      # Пул соединений оптимизированный для облака
      SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: ${DB_POOL_MAX_SIZE:-8}
      SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: ${DB_POOL_MIN_IDLE:-2}
      SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: ${DB_CONNECTION_TIMEOUT:-30000}
      SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT: ${DB_IDLE_TIMEOUT:-300000}
      SPRING_DATASOURCE_HIKARI_MAX_LIFETIME: ${DB_MAX_LIFETIME:-1200000}
      SPRING_DATASOURCE_HIKARI_LEAK_DETECTION_THRESHOLD: ${DB_LEAK_DETECTION_THRESHOLD:-60000}

      # S3 Timeweb настройки
      TIMEWEB_S3_ACCESS_KEY: ${TIMEWEB_S3_ACCESS_KEY:-AJK63DSBOEBQD3IVTLOT}
      TIMEWEB_S3_SECRET_KEY: ${TIMEWEB_S3_SECRET_KEY:-eOkZ8nzUkylhcsgPRQVJdr8qmvblxvaq7zoEcNpk}
      TIMEWEB_S3_ENDPOINT: ${TIMEWEB_S3_ENDPOINT:-https://s3.twcstorage.ru}
      TIMEWEB_S3_BUCKET: ${TIMEWEB_S3_BUCKET:-f9c8e17a-pizzanat-products}
      TIMEWEB_S3_PUBLIC_URL: ${TIMEWEB_S3_PUBLIC_URL:-https://s3.twcstorage.ru/f9c8e17a-pizzanat-products}

      # Кэширование
      SPRING_CACHE_TYPE: ${CACHE_TYPE:-simple}

      # JWT настройки
      JWT_SECRET: ${JWT_SECRET:-"YTg1MmViNjM0MWY5MTk4NTk1OWM4YzhjZTRlMjIzMTZmNWI1ODk3YmY3YmI3NjhjNWFmYTU1NDYzY2E3OGVmMg=="}

      # Логирование оптимизированное для production
      LOGGING_LEVEL_ROOT: ${LOG_LEVEL_ROOT:-WARN}
      LOGGING_LEVEL_COM_BAGANOV: ${LOG_LEVEL_APP:-INFO}
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB: ${LOG_LEVEL_SPRING_WEB:-WARN}
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: ${LOG_LEVEL_SPRING_SECURITY:-WARN}
      LOGGING_PATTERN_CONSOLE: ${LOG_PATTERN:-"%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"}

      # Actuator для мониторинга
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: ${ACTUATOR_ENDPOINTS:-health,info,metrics}
      MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: ${ACTUATOR_HEALTH_DETAILS:-never}
      MANAGEMENT_ENDPOINT_HEALTH_ENABLED: ${ACTUATOR_HEALTH_ENABLED:-true}
      MANAGEMENT_SERVER_PORT: ${ACTUATOR_PORT:-8080}

      # Spring Boot оптимизации
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${JPA_DDL_AUTO:-validate}
      SPRING_JPA_SHOW_SQL: ${JPA_SHOW_SQL:-false}
      SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_BATCH_SIZE: ${JPA_BATCH_SIZE:-25}
      SPRING_JPA_PROPERTIES_HIBERNATE_ORDER_INSERTS: ${JPA_ORDER_INSERTS:-true}
      SPRING_JPA_PROPERTIES_HIBERNATE_ORDER_UPDATES: ${JPA_ORDER_UPDATES:-true}
      SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_BATCH_VERSIONED_DATA: ${JPA_BATCH_VERSIONED_DATA:-true}
      SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_TIME_ZONE: ${JPA_TIMEZONE:-Europe/Moscow}

      # Telegram Gateway настройки
      TELEGRAM_GATEWAY_ENABLED: ${TELEGRAM_GATEWAY_ENABLED:-true}
      TELEGRAM_GATEWAY_ACCESS_TOKEN: ${TELEGRAM_GATEWAY_ACCESS_TOKEN:-AAGCGwAAIlEzNcCeEbrV5r-w65s_0edegXThOhJ2nq-eBw}
      TELEGRAM_GATEWAY_MESSAGE_TTL: ${TELEGRAM_GATEWAY_TTL:-300}
      TELEGRAM_GATEWAY_CALLBACK_URL: ${TELEGRAM_GATEWAY_CALLBACK_URL:-https://debaganov-pizzanat-0177.twc1.net/api/v1/auth/telegram-gateway/callback}
      TELEGRAM_GATEWAY_TIMEOUT_SECONDS: ${TELEGRAM_GATEWAY_TIMEOUT:-10}
      TELEGRAM_GATEWAY_MAX_RETRY_ATTEMPTS: ${TELEGRAM_GATEWAY_RETRIES:-3}

      # Telegram Auth настройки - ОТКЛЮЧЕНЫ для полного перехода на Long Polling
      TELEGRAM_AUTH_ENABLED: ${TELEGRAM_AUTH_ENABLED:-false}
      TELEGRAM_AUTH_BOT_TOKEN: ${TELEGRAM_AUTH_BOT_TOKEN:-7819187384:AAGJNn0cwfJ7Nsv_N25h75eggEmqmD5WZG4}
      TELEGRAM_AUTH_BOT_USERNAME: ${TELEGRAM_AUTH_BOT_USERNAME:-PizzaNatBot}
      TELEGRAM_AUTH_WEBHOOK_URL: ${TELEGRAM_AUTH_WEBHOOK_URL:-https://debaganov-pizzanat-0177.twc1.net/api/v1/telegram/webhook}
      TELEGRAM_AUTH_WEBHOOK_ENABLED: ${TELEGRAM_AUTH_WEBHOOK_ENABLED:-false}
      TELEGRAM_AUTH_TOKEN_TTL_MINUTES: ${TELEGRAM_AUTH_TTL:-10}
      TELEGRAM_AUTH_RATE_LIMIT_PER_HOUR: ${TELEGRAM_AUTH_RATE_LIMIT:-5}

      # Exolve SMS API настройки
      EXOLVE_API_KEY: ${EXOLVE_API_KEY:-eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJRV05sMENiTXY1SHZSV29CVUpkWjVNQURXSFVDS0NWODRlNGMzbEQtVHA0In0.eyJleHAiOjIwNjU1MTM0MTMsImlhdCI6MTc1MDE1MzQxMywianRpIjoiMzIyNDBhZTAtNzU2Ni00NDhkLWEzZGUtYjFjZDBjODlkNTU0IiwiaXNzIjoiaHR0cHM6Ly9zc28uZXhvbHZlLnJ1L3JlYWxtcy9FeG9sdmUiLCJhdWQiOiJhY2NvdW50Iiwic3ViIjoiZDZkYjE4ZDEtOWRhNS00NjRmLWI0ODYtMjI5NGQzMDk2ODI5IiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiY2IxNGFjMTQtODU4OS00MjkzLWJkZjktNGE3M2VkYTRmMzQxIiwic2Vzc2lvbl9zdGF0ZSI6ImUzM2EwYzY1LWFkYTctNGU1My1iYmRmLTQzNDJhNTk0OTE1OCIsImFjciI6IjEiLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsiZGVmYXVsdC1yb2xlcy1leG9sdmUiLCJvZmZsaW5lX2FjY2VzcyIsInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJleG9sdmVfYXBwIHByb2ZpbGUgZW1haWwiLCJzaWQiOiJlMzNhMGM2NS1hZGE3LTRlNTMtYmJkZi00MzQyYTU5NDkxNTgiLCJ1c2VyX3V1aWQiOiI4NDY2MzRkNy0zYTNlLTRiMzMtODdkNy01MDgzZGRlNmYxOWIiLCJjbGllbnRJZCI6ImNiMTRhYzE0LTg1ODktNDI5My1iZGY5LTRhNzNlZGE0ZjM0MSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiY2xpZW50SG9zdCI6IjE3Mi4xNi4xNjEuMTkiLCJhcGlfa2V5Ijp0cnVlLCJhcGlmb25pY2Ffc2lkIjoiY2IxNGFjMTQtODU4OS00MjkzLWJkZjktNGE3M2VkYTRmMzQxIiwiYmlsbGluZ19udW1iZXIiOiIxMzMyNTgzIiwiYXBpZm9uaWNhX3Rva2VuIjoiYXV0ZDJlYTgxNGItMWM4Zi00ODRkLWE0MjgtMjY5YTZjOWM2NmY2IiwicHJlZmVycmVkX3VzZXJuYW1lIjoic2VydmljZS1hY2NvdW50LWNiMTRhYzE0LTg1ODktNDI5My1iZGY5LTRhNzNlZGE0ZjM0MSIsImN1c3RvbWVyX2lkIjoiMTM1ODk5IiwiY2xpZW50QWRkcmVzcyI6IjE3Mi4xNi4xNjEuMTkifQ.AFj1waE8M77SL26g9poSbRYEWeiV9Wy2ZonUnI4JJDF4uBP1D90YjTUOayHCPRbryBp6gU-cszAndQMlQsT5JLNhs88X7uo08XTY52Q9ghfdpEH22uG5AFxtWTr5450TfgLyl38goA76Xpd88xu3SHUJFEaScSGUjLaoZ1TKmvDnzdG1ZExtiARhUNRQ0eqlfkkfmYDiq_injddMk1Qub6TfC4zH4O2C0o4rUr9hIruXZe9ciKZAzZ_2hdys52vV8dN99OY5ghVRyysPAo05lScPDDMEpT2F6BwfZEQSH8r7WqOU3acxSI64gqmOFTczGZlsE7o09b_NlehqXIuHDg}
      EXOLVE_SENDER_NAME: ${EXOLVE_SENDER_NAME:-+79304410750}
      EXOLVE_API_URL: ${EXOLVE_API_URL:-https://api.exolve.ru/messaging/v1}
      EXOLVE_TIMEOUT_SECONDS: ${EXOLVE_TIMEOUT:-10}
      EXOLVE_RETRY_MAX_ATTEMPTS: ${EXOLVE_RETRIES:-3}

      # SMS Settings
      SMS_CODE_LENGTH: ${SMS_CODE_LENGTH:-4}
      SMS_CODE_TTL_MINUTES: ${SMS_CODE_TTL:-10}
      SMS_RATE_LIMIT_PER_HOUR: ${SMS_RATE_LIMIT:-3}
      SMS_MAX_ATTEMPTS: ${SMS_MAX_ATTEMPTS:-3}

      # Telegram Bot настройки (основные уведомления) - ИСПОЛЬЗУЕМ TELEGRAM_AUTH_BOT_TOKEN
      TELEGRAM_ENABLED: ${TELEGRAM_ENABLED:-true}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_AUTH_BOT_TOKEN:-7819187384:AAGJNn0cwfJ7Nsv_N25h75eggEmqmD5WZG4}
      TELEGRAM_API_URL: ${TELEGRAM_API_URL:-https://api.telegram.org/bot}

      # Telegram Long Polling настройки (команды бота) - ВКЛЮЧЕНЫ для авторизации и уведомлений
      TELEGRAM_LONGPOLLING_ENABLED: ${TELEGRAM_LONGPOLLING_ENABLED:-true}
      TELEGRAM_BOT_ENABLED: ${TELEGRAM_BOT_ENABLED:-true}
      TELEGRAM_BOT_USERNAME: ${TELEGRAM_BOT_USERNAME:-PizzaNatBot}

      # Админский Telegram Bot настройки - ВКЛЮЧЕН для административных уведомлений
      TELEGRAM_ADMIN_BOT_ENABLED: ${TELEGRAM_ADMIN_BOT_ENABLED:-true}
      TELEGRAM_ADMIN_BOT_TOKEN: ${TELEGRAM_ADMIN_BOT_TOKEN:-8052456616:AAEoAzBfr3jRpylDmxR-azNBSqimthPCHeg}
      TELEGRAM_ADMIN_BOT_USERNAME: ${TELEGRAM_ADMIN_BOT_USERNAME:-PizzaNatOrders_bot}
      TELEGRAM_ADMIN_BOT_MAX_RETRIES: ${TELEGRAM_ADMIN_BOT_RETRIES:-3}
      TELEGRAM_ADMIN_BOT_TIMEOUT_SECONDS: ${TELEGRAM_ADMIN_BOT_TIMEOUT:-30}

    ports:
      - "${SERVER_PORT:-8080}:${SERVER_PORT:-8080}"

    networks:
      - pizzanat-network

  # Nginx для продакшена с поддержкой CORS
  nginx:
    image: nginx:alpine
    container_name: pizzanat-nginx-prod
    restart: unless-stopped
    depends_on:
      app:
        condition: service_healthy
    command: |
      sh -c "
      cat > /etc/nginx/conf.d/default.conf << 'EOF'
      upstream app {
          server app:8080;
      }

      server {
          listen 80;
          server_name _;
          client_max_body_size 20M;

          location / {
              # Обработка preflight запросов
              if (\$$request_method = 'OPTIONS') {
                  add_header 'Access-Control-Allow-Origin' 'https://pizzanat.ru' always;
                  add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS, PATCH' always;
                  add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type, X-Requested-With, Accept, Origin, X-Auth-Token, Cache-Control' always;
                  add_header 'Access-Control-Allow-Credentials' 'true' always;
                  add_header 'Access-Control-Max-Age' '3600' always;
                  add_header 'Content-Type' 'text/plain charset=UTF-8';
                  add_header 'Content-Length' '0';
                  return 204;
              }

              proxy_pass http://app;
              proxy_set_header Host \$$host;
              proxy_set_header X-Real-IP \$$remote_addr;
              proxy_set_header X-Forwarded-For \$$proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto \$$scheme;
              
              # Добавляем CORS заголовки для всех ответов
              add_header 'Access-Control-Allow-Origin' 'https://pizzanat.ru' always;
              add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS, PATCH' always;
              add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type, X-Requested-With, Accept, Origin, X-Auth-Token, Cache-Control' always;
              add_header 'Access-Control-Allow-Credentials' 'true' always;
              
              proxy_connect_timeout 60s;
              proxy_send_timeout 60s;
              proxy_read_timeout 60s;
          }
      }
      EOF
      nginx -g 'daemon off;'
      "
    ports:
      - "80:80"
    networks:
      - pizzanat-network

networks:
  pizzanat-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
  minio-data:
