spring:
  profiles:
    active: dev
  jackson:
    serialization:
      write-dates-as-timestamps: false

s3:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: pizzanat
  public-url: http://localhost

---
spring:
  config:
    activate:
      on-profile: prod
  # Отключаем Redis для prod
  cache:
    type: simple
  data:
    redis:
      repositories:
        enabled: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
  jackson:
    serialization:
      write-dates-as-timestamps: false

  datasource:
    # Эти значения перезаписываются переменными окружения в продакшене
    url: jdbc:postgresql://localhost:5432/pizzanat
    username: pizzanat
    password: pizzanat_password
    driver-class-name: org.postgresql.Driver

timeweb:
  s3:
    endpoint: https://s3.twcstorage.ru
    access-key: ${TIMEWEB_S3_ACCESS_KEY:AJK63DSBOEBQD3IVTLOT}
    secret-key: ${TIMEWEB_S3_SECRET_KEY:eOkZ8nzUkylhcsgPRQVJdr8qmvblxvaq7zoEcNpk}
    bucket: f9c8e17a-pizzanat-products
    public-url: https://s3.twcstorage.ru/f9c8e17a-pizzanat-products
