spring:
  profiles:
    active: dev

minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: pizzanat
  public-url: http://localhost:9000

---
spring:
  config:
    activate:
      on-profile: prod

minio:
  endpoint: https://s3.twcstorage.ru
  access-key: ${TIMEWEB_S3_ACCESS_KEY:AJK63DSBOEBQD3IVTLOT}
  secret-key: ${TIMEWEB_S3_SECRET_KEY:eOkZ8nzUkylhcsgPRQVJdr8qmvblxvaq7zoEcNpk}
  bucket: f9c8e17a-pizzanat-products
  public-url: https://s3.twcstorage.ru
